name: Build 'n Publish

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths-ignore:
      - 'pyproject.toml'
      - 'bumpver.toml'

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install bumpver & poetry
        run: pip3 install bumpver poetry poetry-plugin-bundle
      - name: Setup git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Install dependencies
        run: poetry install

      #   -- Testing & Linting --
      - name: Lint
        run: |
          poetry run flake8 podaac/
          poetry run pylint podaac/

      #   -- Version Bumping --
      - name: Bump alpha version
        if: github.ref == 'refs/heads/develop'
        run: |
          TAG=$(bumpver show -e | awk -F= '$1 == "TAG" {print $2};')
          if [ $TAG == 'final' ]; then
            # Bump patch version first then append tag
            bumpver update --patch --tag alpha --tag-num
          else
            bumpver update --tag alpha --tag-num
          fi
      - name: Bump rc version
        if: startsWith(github.ref, 'refs/heads/release/')
        run: bumpver --tag rc --tag-num
      - name: Release version
        if: github.ref == 'refs/heads/main'
        run: bumpver --tag final
